nelmio_api_doc:
    documentation:
        info:
            title: diyhrt.cafe API
            description: An API that automatically scrapes price data
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$)/v1(?!/user(.*)$) # Accepts routes under /api except /api/doc and /api/v1/user
